"""Write repair handoff and preserve old delivery integrity; never self-accept."""
from pathlib import Path
import datetime as dt, hashlib, json, os, sqlite3
HERE=Path(__file__).resolve().parent;PLAN=HERE.parents[1];WIKI=HERE.parents[4]
baseline=json.loads((HERE/'before_v3.json').read_text(encoding='utf-8'));OLD=Path(baseline['old_output_root']);OUT=Path(baseline['v3_output_root'])
SKILL=Path.home()/'.agents/skills/revenue-forecast';CANON=Path.home()/'Projects/revenue-forecast'
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2),encoding='utf-8')
def artifact(p,role):return {'absolute_path':str(p.resolve()),'sha256':sha(p),'bytes':p.stat().st_size,'role':role}
i=read(OUT/'input.json');f=read(OUT/'forecast.json');bindings=read(HERE/'v3_claim_binding_index.json');verification=read(HERE/'v3_delivery_verification.json')
checks=[]
for category in ('old_temp_artifacts','old_engineering_artifacts','raw_and_config_baseline'):
 for before in baseline[category]:
  p=Path(before['path']);row={**before,'category':category,'after_sha256':sha(p) if p.exists() else None,'after_bytes':p.stat().st_size if p.exists() else None}
  row['unchanged']=row['sha256']==row['after_sha256'] and row['bytes']==row['after_bytes'];checks.append(row)
assert all(x['unchanged'] for x in checks),'A protected old artifact changed'
write(HERE/'after_v3_integrity.json',{'timestamp_utc':dt.datetime.now(dt.timezone.utc).isoformat(),'old_temp_and_engineering_and_raw_config':'UNCHANGED','checks':checks,'allowed_producer_change':'append-only source-facts assertion, raw bytes unchanged','allowed_logs_append':['events.jsonl','commands/index.jsonl','processes/*']})
# Actual read-only producer audit: preserve the old row and show explicit supersession.
db=(WIKI/'.source_catalog/catalog.sqlite3').resolve();conn=sqlite3.connect(db.as_uri()+'?mode=ro',uri=True);conn.row_factory=sqlite3.Row;conn.execute('PRAGMA query_only=ON')
oldid='sa-f5cc0cf223e6460596a950f65d89f054';newid=read(HERE/'v3_source_facts_2025.receipt.json')['new_response']['assertion_id']
rows=[dict(conn.execute('SELECT * FROM source_metadata_assertions WHERE assertion_id=?',(aid,)).fetchone()) for aid in (oldid,newid)];conn.close()
review_before=next(x for x in read(PLAN/'reviews/HK-00700/independent_current_producer_rows.json')['rows']['source_metadata_assertions'] if x['assertion_id']==oldid)
assert rows[0]==review_before,'Old assertion changed'
assert rows[1]['supersedes_assertion_id']==oldid
assert rows[1]['fiscal_year']==2025 and rows[1]['language']=='zh'
write(HERE/'v3_source_facts_producer_after.json',{'read_mode':'sqlite mode=ro / PRAGMA query_only=ON','database':str(db),'old_assertion_unchanged':True,'new_supersedes_old':True,'rows':rows})

claims=i['evidence_claims'];by_target=lambda target:[c['claim_id'] for c in claims if c['target_id']==target and c['claim_id'].startswith('v3_')]
findings=[]
def finding(n,status,change,ids=None,locators=None,remaining=None,artifacts=None):
 findings.append({'id':f'HK-R{n:02d}','executor_status':status,'implementation':change,'claim_ids':ids or [],'original_locators':locators or [],'evidence_artifacts':[str(x) for x in artifacts or []],'remaining_reason':remaining,'independent_review':'PENDING; executor does not sign own work'})
finding(1,'implemented_pending_independent_review','Bound259/264 fee subscriptions AND quarter-average daily definition separately from H1 revenue contraction.',by_target('paid_social_stabilization_contrary'),['H1 PDF6/printed5 subscription table and footnote','H1 PDF47/printed46 Social revenue comparative'])
finding(2,'implemented_pending_independent_review','Full Supercell/FX/constant-currency paragraph and annual33%/32% bound to Tencent contrary node. Independent peer franchise/net-revenue observations have a separate one-step node, no market-share/displacement assertion.',by_target('evergreen_and_launch_monetization_contrary')+by_target('games_independent_peer_context'),['H1 PDF10/printed9 complete international paragraph','Annual PDF9/printed8','NetEase release full H1 financial and games-franchise sections'])
finding(3,'implemented_pending_independent_review','Two context-only annual reported parameters normalize group customer6.5%/3.4% into ratios; claims explicitly associated with customers gap. NetEase H1 net-gaming+8.3% claim associated with industry_market gap and peer context; no use as direct model coefficient.',by_target('context_group_top5_customer_revenue_share')+by_target('context_group_largest_customer_revenue_share')+next(x['evidence_claim_ids'] for x in i['research_coverage'] if x['dimension']=='industry_market'),['Annual PDF80/printed79 group customer concentration','NetEase first-half financial highlights'],remaining='Segment billable customer denominators, total market/share and comparable peer perimeter still data gaps.')
finding(4,'implemented_pending_independent_review','All five aggregate bases now separately bind general control-transfer timing and principal/agent gross-net, plus segment-specific timing. Games/Social also bind platform and third-party VAS presentation. No second transformation.',[c['claim_id'] for c in claims if c['target_type']=='recognition_policy' and c['claim_id'].startswith('v3_')],['Annual Note2.22 PDF165-167/printed164-166'])
finding(5,'implemented_pending_independent_review','All36 future Games/Social/Marketing/FBS rationales bind complete annual/H1/Q2/AI-ad/GPU paragraphs per actual parameter. All original45 future rates and6 bases unchanged.',[c for x in bindings['assumption_bindings'].values() for c in x['added_claim_ids']],['Annual PDF9/196','H1 PDF6/10/47','Corporate Overview PDF12/15','NetEase full release'],artifacts=[HERE/'v3_claim_binding_index.json',OUT/'context_inventory.json'])
finding(6,'unresolved_external_official_provenance','Exactly3 bounded official HTTP requests: registered URL404, official archive contains observedTC link, PDF linkHTTP200982-byte HTML. No PDF magic or same-SHA proof; no producer URL update.',remaining='Authentic current official same-SHA PDF and exact original publication metadata inaccessible. Do not claim repaired, treat as provenance limitation.',artifacts=[HERE/'v3_official_auth.json'])
finding(7,'representation_corrected_exact_day_unverified','Exact-day claim removed for full H1 book/Corporate Overview, and conservatively for legacy FY2025. Required published_date field explicitly denotes available-as-of upper bound2026-10-08, not a release event; date_uncertainty retains old board/filename/legacy assertions. Actual live/asof reads establish cutoff availability.',remaining='Exact primary publication days remain UNKNOWN. A future runtime nullable publication-date/availability contract would express this without a mandatory-date surrogate; no runtime rewrite in HK repair.',artifacts=[HERE/'v3_claim_binding_index.json'])
finding(8,'implemented_pending_independent_review',f'Actual FY2025 cover/summary rendered and viewed; public source-facts producer appended{newid} superseding{oldid}. Read-only query proves old row unchanged, new correct fiscal-year/language and observation.',locators=['Actual FY2025 PDF1cover andPDF4summary'],artifacts=[HERE/'v3_source_facts_2025.request.json',HERE/'v3_source_facts_2025.receipt.json',HERE/'v3_source_facts_producer_after.json',OUT/'FY2025_page_1_visual.png',OUT/'FY2025_page_4_visual.png'])
finding(9,'blocked_external_adapter','Existing capped RF→FF→CWP missing-H1 request still blocks before Dayu discover; no new provider call, no downloaded_new→reuse demonstration. No budget relaxation/Dayu modification.',remaining='External Dayu adapter lacks bounded capabilities. Official supplemental route success does not attest FF/Dayu download.',artifacts=[HERE/'request_interim_2026_no_language.json'])
finding(10,'partial_communication_coverage','Exact FY2026Q2 companion zero-cost unavailable/provider_calls0, ET child0 and no call body. Unavailable earnings deck/webcast and incomplete announcements interval preserved. Empty targets only for actually opened originals.',remaining='No latest transcript and no exhaustive Apr9–Oct8 announcements. Missing management-target risk remains explicit.',artifacts=[HERE/'ff_latest_companion.response.json',HERE/'communication_coverage.json'])
finding(11,'blocked_canonical_processing','Real raw verify/open and task-local deterministic extraction kept separate from CWP Worker/normalized EvidenceSpan/narrative pipeline. Retired absent derivatives and earlier invalid-JSON failure are not consumed or claimed fixed.',remaining='No bounded canonical producer processing run in this HK repair; owner/MAIN must supply if full processing success is required.',artifacts=[HERE/'deterministic_local_parse.json',PLAN/'reviews/HK-00700/independent_current_producer_rows.json'])
finding(12,'conditional_fallback_scope_disclosed','Five direct_growth paths explicitly conditional, with denied invented operating denominators and zero explicit-model/backtest credit. All15 H2 residuals, all45 curve values and15 shock sensitivities independently checked. Uncalibrated FY2027/28 fade/stabilization and risk assumptions disclosed.',remaining='No accuracy certification, calibrated prediction interval or causal coefficient estimate. Only one differently scoped peer reference, incomplete management communications and no future actuals.',artifacts=[HERE/'v3_delivery_verification.json',OUT/'forecast.md'])
finding(13,'resolved_by_MAIN_retested','Current installed publication_registry.py actual CLI audit(exit0) and chain/anchor audit below, using separate v3 registry. MAIN reported RF08673cf8/green; HK changed no runtime.',artifacts=[HERE/'v3_audit.stdout.txt',HERE/'v3_audit.stderr.txt'])

registry=[json.loads(line) for line in (OUT/'publications.jsonl').read_text(encoding='utf-8').splitlines() if line.strip()]
def canonical_sha(v):return hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode('utf-8')).hexdigest()
previous=None
for entry in registry:
 assert entry['prev_line_sha256']==previous
 payload={k:v for k,v in entry.items() if k!='line_sha256'};assert canonical_sha(payload)==entry['line_sha256'];previous=entry['line_sha256']
assert any(e['artifact_type']=='forecast' and e['input_sha256']==f['input_sha256'] and e['result_sha256']==f['result_sha256'] for e in registry)
assert any(e['artifact_type']=='snapshot' and e['input_sha256']==f['input_sha256'] for e in registry)
write(HERE/'v3_registry_integrity.json',{'effective_env':'REVENUE_PUBLICATION_REGISTRY','effective_path':str(OUT/'publications.jsonl'),'registry_sha256':sha(OUT/'publications.jsonl'),'entry_count':len(registry),'chain':'PASS','forecast_snapshot_anchors':'PASS','audit_exit':0,'audit_stdout_empty_means_no_problems':True,'current_installed_registry_runtime_sha256':sha(SKILL/'scripts/publication_registry.py'),'MAIN_reported_commit':'08673cf8','commit_claim_source':'MAIN message; HK did no Git operation','entries':registry})

runtime=[]
for p in (SKILL/'scripts').rglob('*.py'):
 rel=p.relative_to(SKILL);q=CANON/rel
 runtime.append({'installed_path':str(p),'canonical_path':str(q),'installed_sha256':sha(p),'canonical_sha256':sha(q) if q.exists() else None,'matches_canonical':q.exists() and sha(q)==sha(p)})
write(HERE/'v3_runtime_inventory.json',{'engine_version':f['engine_version'],'schema_version':f['schema_version'],'current_runtime':runtime,'mismatches':[x for x in runtime if not x['matches_canonical']],'owner':'MAIN; HK did not write runtime/config/installation'})
key_names=['lint','hash-check','validate','forecast','snapshot','audit','strong-calc']
commands=[json.loads(line) for line in (HERE/'commands/index.jsonl').read_text(encoding='utf-8').splitlines()]
v3_commands=[x for x in commands if x['event']=='finish' and 'HK-v3-' in x['label']]
for name in key_names:
 matches=[x for x in v3_commands if x['label']=='HK-v3-'+name or (name=='strong-calc' and x['label']=='HK-v3-strong-render-independent-calc')]
 assert matches and matches[-1]['returncode']==0,name
repair={'schema_version':'1.0','company':'Tencent00700','as_of_date':'2026-10-08','agent_id':'/root/rf_hk_execution','review_origin':str(PLAN/'reviews/HK-00700/review.json'),'repair_scope':'single v3 batch; old artifacts preserved','status':'partial_pending_independent_review','findings':findings,'formal_runtime_commands':[{'label':x['label'],'id':x['id'],'returncode':x['returncode'],'outputs':x['outputs']} for x in v3_commands],'unchanged_old_artifact_count':len(checks),'fact_binding_index':str(HERE/'v3_claim_binding_index.json'),'claim_context_count':len(read(OUT/'context_inventory.json')['contexts']),'all_claim_count':len(claims),'all_rationale_assumptions':36,'original_numeric_parameters_unchanged':51,'context_only_new_reported_parameters':2,'future_accuracy_claimed':False,'CWP_canonical_research_state_written':False,'paid_external_LLM_calls':0,'FMP_provider_calls':0,'Dayu_provider_calls':0,'ET_child_calls':0,'provider_cost_usd':0,'main_owned_followups':['bounded Dayu capability gap','complete call and material announcements coverage','canonical bounded Worker processing','official FY2025 same-SHA authentication','runtime publication exact-day versus availability semantics'],'independent_reviewer_required':True}
write(HERE/'repair_v3.json',repair)
steps=read(HERE/'skill_step_matrix.json')
steps['version']='v3';steps['status']='partial_pending_independent_review';steps['research_output_root']=str(OUT)
for row in steps['steps']:
 row['v3_evidence']=[str(HERE/'repair_v3.json'),str(HERE/'v3_delivery_verification.json')]
 if row['step']=='1':row['v3_status']='done_with_explicit_publication_uncertainty';row['v3_evidence'].append(str(HERE/'v3_claim_binding_index.json'))
 elif row['step'] in ('1A','3'):row['v3_status']='partial_supply_communication_canonical_processing'
 else:row['v3_status']='implemented_pending_independent_review'
write(HERE/'skill_step_matrix_v3.json',steps)
write(HERE/'fact_checks_v3.json',{'scope':'Engineering QA inventory; formal research lives only in isolated TEMP/v3','source_claims':claims,'parameter_checks':[{'parameter_id':p['parameter_id'],'kind':p['kind'],'value':p['value'],'period':p['period'],'unit':p['unit'],'scenario':p['scenario'],'claim_ids':p['claim_ids'],'definition':p['definition'],'value_status':'unchanged original input' if not p['parameter_id'].startswith('context_') else 'new reported context only, not used in revenue engine'} for p in i['parameters']],'exact_original_context_verification':verification['all_claim_original_context_checks'],'derived_historical_facts':bindings['numeric_derived_facts'],'H2_requirements':verification['H2_requirements'],'future_rates':'analyst conditional scenarios, uncalibrated, no fabricated operating denominator','context_normalization':'customer6.5%/3.4% divided by100 to0.065/0.034, GROUP revenue perimeter; peer8.3% is NetEase H1 net games+relatedVAS company observation, not market share','all325_claims_checked':True})
report=['# HK00700 单批 v3 修复交接','', '执行者完成实现与测试，尚未获独立复查签收。完整供应链/处理/沟通仍为 partial。旧版本和原件不变。','', '## 每项初审问题','', '|问题|执行结果|处理及未解决范围|','|---|---|---|']
for x in findings:report.append('|'+x['id']+'|'+x['executor_status']+'|'+(x['implementation']+' '+(x['remaining_reason'] or '')).replace('|','/')+'|')
report += ['', '## 验证与数字边界','', '- 实际 lint、--check哈希、validate-only、engine、snapshot、registry audit、强输入验证、同源render全部退出0。325条claim的原文包含/哈希/capture绑定逐条检查；全部45业务路径、9公司年合计、15敏感性及15个H2要求复算通过。', '- 原51数值参数、原45未来增长率、全部收入/CAGR/敏感性结果保持；新增2个仅作上下文的FY2025集团客户集中度reported_fact，未进入收入模型。confidence仍64，显式模型/历史准确率为0；不代表未来成功概率。', '- 日期字段2026-10-08明确是信息截至日可取得的保守上界，非实际发布事件。旧的2026-08-12董事签署/2026-09-16文件名/2026-04-09旧producer断言均保留在date_uncertainty；不伪造确切公开日期。', '- 官方字节认证仅3次HTTP GET，累计196676B，$0；旧URL404/current官方PDF982B HTML不可作PDF。没有更新生产source_url。没有电话会正文或Dayu child，没有canonical Worker完成证明。', '', '## 独立复查入口','', f'- 新研究文件：`{OUT}`（input.json/forecast.json/forecast.md/snapshot.json）。', '- repair_v3.json：13finding结果、精确claim IDs、原文locator、未解决原因。v3_claim_binding_index.json：36parameter→完整claim/context映射。TEMP/v3/context_inventory.json含全部原文上下文。', '- v3_delivery_verification.json：每条claim和所有算术结果；v3_registry_integrity.json：正式注册链与anchors；after_v3_integrity.json：旧文件/原件/配置逐一SHA与bytes。', '- 公共producer新request/receipt及只读数据库新旧row在v3_source_facts_*；独立复核应验证旧assertion不变、新assertion明确supersedes。', '- 复查人只读此输入和原文重跑即可；不要运行旧build_input.py/run_step.py写穿旧产物，也不要运行v3_setup.py再次冻结baseline。', '', '## 范围与环境','', f'- `REVENUE_PUBLICATION_REGISTRY={OUT / "publications.jsonl"}`只对子进程生效。`CWP_AUDIT_PROCESS_DIR={HERE / "processes"}`，PYTHONPATH前置共享process_trace并保留原值。', '- 输出在独立TEMP，工程记录在唯一HK执行目录。所有共享代码、生产配置、原始文档、Dayu和邻仓WIP没有写入。标准source-facts追加是唯一已授权producer写操作。', '- 未来完整年度实际未知，不运行伪造actuals回测。不新增外部付费LLM，不改已配置模型/profile。']
(HERE/'repair_v3.md').write_text('\n'.join(report)+'\n',encoding='utf-8')
manifest={'schema_version':'1.0','company':'Tencent Holdings Limited','market':'HK','security_id':'00700','agent_id':'/root/rf_hk_execution','as_of_date':'2026-10-08','status':'partial_pending_independent_review','output_root':str(OUT),'primary_artifacts':[artifact(OUT/name,role) for name,role in [('input.json','independently repaired input'),('forecast.json','actual RF validated result'),('forecast.md','same JSON deterministic render'),('snapshot.json','immutable v3 snapshot')]],'registry':artifact(OUT/'publications.jsonl','own append-only registry'),'runtime_inventory_path':str(HERE/'v3_runtime_inventory.json'),'runtime_version':f['engine_version'],'schema_version_runtime':f['schema_version'],'current_registry_runtime_sha256':sha(SKILL/'scripts/publication_registry.py'),'source_capture_receipts_preserved':True,'sources':[{'source_id':x['source_id'],'raw_sha256':x['capture']['snapshot_sha256'],'capture_receipt_sha256':x['capture']['receipt_sha256'],'url':x['url'],'published_date_field':x['published_date'],'date_uncertainty':x.get('date_uncertainty'),'scope':'independent website supplement' if x.get('supplemental_route') else 'actual RF→FF→CWP raw reuse'} for x in i['sources']],'repair_path':str(HERE/'repair_v3.json'),'repair_markdown_path':str(HERE/'repair_v3.md'),'claim_binding_index_path':str(HERE/'v3_claim_binding_index.json'),'verification_path':str(HERE/'v3_delivery_verification.json'),'unchanged_old_bytes_path':str(HERE/'after_v3_integrity.json'),'unchanged_old_artifact_count':len(checks),'old_manifest':artifact(HERE/'manifest.json','immutable previous execution manifest'),'command_index':str(HERE/'commands/index.jsonl'),'process_trace_dir':str(HERE/'processes'),'environment':{'REVENUE_PUBLICATION_REGISTRY':str(OUT/'publications.jsonl'),'CWP_AUDIT_PROCESS_DIR':str(HERE/'processes'),'PYTHONPATH_prefix':str(PLAN/'process_trace')},'full_pipeline_status':{'local_raw_virtual_reuse':'PASS from actual earlier receipts; unchanged bytes','deterministic_local_parse':'PASS in ownedTEMP','RF_formal_model':'PASS execution verification, independent acceptance pending','Dayu_bounded_missing_download':'BLOCKED','ET_latest_call':'NOT_AVAILABLE;provider_calls0/child0','all_announcements':'PARTIAL','CWP_canonical_Worker':'BLOCKED/not demonstrated','FY2025_sameSHA_official_authentication':'BLOCKED','exact_full_H1_and_Corporate_publication_days':'UNKNOWN, explicit conservative asof bounds'},'calls_and_cost':{'v3_official_HTTP_requests':3,'v3_official_HTTP_bytes':196676,'paid_LLM_calls':0,'FMP_provider_calls':0,'provider_cost_usd':0},'independent_review':'REQUIRED, never executor signed','ended_at':dt.datetime.now(dt.timezone.utc).isoformat()}
write(HERE/'manifest_v3.json',manifest)
manifest['step_matrix_path']=str(HERE/'skill_step_matrix_v3.json');manifest['facts_index_path']=str(HERE/'fact_checks_v3.json')
write(HERE/'manifest_v3.json',manifest)
event={'timestamp_utc':dt.datetime.now(dt.timezone.utc).isoformat(),'agent_id':'/root/rf_hk_execution','step':'v3_repair','action':'write_v3_handoff_not_self_accept','tool':'task-local handoff writer','input_summary':{'findings':13,'claims':325,'original_numeric_parameters':51,'before_after_unchanged':len(checks)},'source_url':None,'artifacts':[str(HERE/'manifest_v3.json'),str(HERE/'repair_v3.json'),str(HERE/'repair_v3.md')],'outcome':'partial_pending_independent_review','error':None}
with (HERE/'events.jsonl').open('a',encoding='utf-8') as z:z.write(json.dumps(event,ensure_ascii=False)+'\n')
print(json.dumps({'manifest':str(HERE/'manifest_v3.json'),'repair':str(HERE/'repair_v3.json'),'old_artifacts_unchanged':len(checks),'findings':len(findings),'new_assertion_id':newid,'runtime_mismatches':len([x for x in runtime if not x['matches_canonical']]),'status':'partial_pending_independent_review'},ensure_ascii=False))
