"""Seal v4 classification acceptance and preserve product/source limitations."""
from pathlib import Path
import datetime as dt,hashlib,json
HERE=Path(__file__).resolve().parent;EX=HERE.parents[1]/'executions/HK-00700'
load=lambda p:json.loads(Path(p).read_text(encoding='utf-8'))
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
support=load(HERE/'recheck_v4_support.json');m=load(EX/'manifest_v4.json');prior=load(HERE/'recheck_v3.json')
checks=[]
def check(id,topic,status,details,evidence=None):checks.append(dict(id=id,topic=topic,status=status,evidence=evidence or [str(HERE/'recheck_v4_support.json')],details=details))
check('V4-01','Exact7 changed input fields and carried evidence closure','PASS','Independent recursive diff equals classification_v4.json exactly: risk evidence_type/inference_distance/conclusion, related Tencent contrary explanation, counterevidence rationale, new risk data_gap and version.325 claim records and53 parameter records are fully equal to sealed v3; original51 numeric records/45 future rates unchanged. V3 original-text audit is inherited by identity; no unnecessary re-extraction.')
check('V4-02','Peer competitive-risk semantics','PASS','contrary describes competitive risk direction, with analogical cross-company inference expressly retained in text. Different company/NET/perimeter, no quantified Tencent displacement/share/payer/ARPPU/magnitude or positive Tencent revenue-mechanism corroboration. This closes HK-V3-R01 and remaining HK-R02 classification.')
check('V4-03','Actual engine quality label and confidence dependency','PASS','Both Games detailed driver and ranked top driver are limited. The exact Games-not-triangulated confidence limitation is restored in JSON. Score64 and all components remain unchanged; only the missing warning returns. Markdown is exact standard render, shows Games limited and independent_peer_competition_risk/contrary plus no-triangulation data_gap; it does not print the confidence JSON limitation verbatim.')
check('V4-04','Strong input-required validation/render and separate real engine replay','PASS','Actual installed validate_published_forecast(f,input), exact render_markdown and strong snapshot validation pass. Own separate TEMP copy and true revenue_forecast CLI exit0 reproduce deterministic payload after only timestamps/signature/receipt fields removed. Sealed v4 originals rehashed after verification unchanged.')
check('V4-05','All unchanged monetary paths/CAGR/sensitivity/allocation','PASS','Complete segment scenario dictionaries,9 company annual totals/CAGR/increments and all15 sensitivity records equal sealed v3 exactly. All5 driver numeric allocations, ranked shares and reconciliation unchanged. CNY million and mixed already-recognized accounting contracts are identical; classification repair adds no revenue effect.')
check('V4-06','Snapshot and real installed registry audit','PASS','Actual v4 snapshot passes strong validator; original registry chain and forecast/snapshot input/result/ID registrations match. Installed publication_registry audit --result exits0; own replay registry is separate. No original registry edits by reviewer.')
check('V4-07','188 old files, sealed reviews and51runtime protection','PASS',f"188 old files including sealed v3 independently rehashed with bytes. Initial and v3 review files remain unchanged.51 installed/canonical runtime files match emitting SHA and each other; no reviewer edits outside own reviews and TEMP. {len(support['commands'])} v4 start/finish command pairs and {len(support['process_traces'])} recorded real child traces inspected; output hashes/bytes verified.")
check('V4-08','Old sources/date uncertainty and conditional-model limits','PASS','Sources/captures/date_uncertainty,history,recognition andcommunication/target ledgers remain exactly equal to v3.2026-10-08 is only a verified cutoff-availability upper bound for FY2025/H1/Corporate, not exact public day or annual sameSHA authentication. H2 residual conditions, missing operating denominators, uncalibrated2027/28 paths and no future accuracy claim remain disclosed.')
for id,topic,details in [('V4-B01','R06/R07 official source authentication and precise dates','FY2025 registeredURL404/currentofficialchallengeHTML still lacks PDFsameSHA; exact annual/H1/Corporate public days remain unknown. V4 does not perform new authentication or update producer URL.'),('V4-B02','R09 bounded Dayu new download and reuse','No bounded missing filing downloaded_new→zero-download-reuse demonstration. Existing rejected provider capability remains blocked; separate official HTTP and annual reuse do not complete this route.'),('V4-B03','R10 ET/call body and full announcements','FY2026Q2 exact companion still zero-cost unavailable/provider_calls0; no ET body or fullApr9–Oct8 announcement interval. No management-target completeness/absence certification.'),('V4-B04','R11 HK canonical Worker/narrative processing','No HK canonical Worker/active derived source chain shown. Existing MSFT49span current-read versus explicit-asof refusal is other-company evidence; it does not close HK processing or forecast consumption.')]:
    check(id,topic,'BLOCKED',details,[str(HERE/'recheck_v3.json'),str(EX/'repair_v4.json')])
closed=prior['closed_findings']+['HK-R02','HK-V3-R01']
remaining=[q for q in prior['remaining_findings'] if q['id']!='HK-R02']
findings=[]
for row in remaining:
    findings.append(dict(id=row['id'],severity='P1' if row['id'] in ['HK-R09','HK-R10'] else 'P2',category='retained_product_source_or_calibration_limit',status=row['status'],description=row['details'],paths=[str(HERE/'recheck_v3.json'),str(EX/'repair_v4.json')],reproduction=['Read unchanged source/capability disclosure and sealed v3 independent review; v4 source and parameter record equality verified.'],requested_fix='Retain this limitation in summaries. Complete only its separately authorized owner/source work; do not claim whole E2E or calibrated future accuracy from classification/math PASS.'))
facts=[dict(claim_or_parameter_id='games_independent_peer_context',source_locator=support['peer_after']['claim_ids'],independent_value=support['peer_after'],unit=None,period='as_of2026-10-08',status='PASS',evidence=[str(HERE/'recheck_v4_support.json')+'#peer_after']),dict(claim_or_parameter_id='Games.evidence_status',source_locator='actual v4 forecast growth_driver_analysis drivers/top_drivers',independent_value='limited',unit=None,period='FY2026–FY2028 conditional model',status='PASS',evidence=[str(HERE/'recheck_v4_support.json')]),dict(claim_or_parameter_id='confidence.score',source_locator='actual v4 confidence',independent_value=64,unit='workflow_score_out_of100',period='as_of2026-10-08',status='PASS',evidence=[str(HERE/'recheck_v4_support.json')]),dict(claim_or_parameter_id='confidence.Games_limitation',source_locator='actual v4 confidence.limitations',independent_value=support['restored_confidence_warning'],unit=None,period='as_of2026-10-08',status='PASS',evidence=[str(HERE/'recheck_v4_support.json')])]
report=dict(schema_version='1.0',reviewer_agent_id='/root/rf_hk_independent_review',executed_agent_id=m['agent_id'],company='Tencent Holdings Limited / 腾讯 / HK00700',reviewed_at=dt.datetime.now(dt.timezone.utc).isoformat(),review_scope='v4 classification and dependent-artifact closure only; initial/v3 sealed findings retained',reviewed_runtime=dict(engine_version='4.1.0',schema_version='3.7',runtime51=support['runtime51']),verdict='PARTIAL',repair_scope_verdict='PASS',model_acceptance='PASS_CONDITIONAL_WITH_EXPLICIT_SOURCE_AND_CALIBRATION_LIMITATIONS',full_product_E2E='PARTIAL',future_predictive_accuracy='UNESTABLISHED',closed_findings=closed,remaining_findings=remaining,new_findings=[],finding_closure=[dict(id='HK-V3-R01',status='CLOSED',details='Risk-classification/engine-label/confidence/snapshot/render/registry dependency closure independently verified.'),dict(id='HK-R02',status='CLOSED',details='V3 corrected factual binding and v4 corrected inference classification; source-period and NET/perimeter distinctions preserved.')],checks=checks,facts=facts,carried_fact_inventory=dict(source_review=str(HERE/'recheck_v3.json'),source_sha256=sha(HERE/'recheck_v3.json'),claims325_records_equal=True,parameters53_records_equal=True,source_date_records_equal=True,history_and_segment_contracts_equal=True),independent_calculations=dict(support_path=str(HERE/'recheck_v4_support.json'),strong_validation=support['strong_input_required'],same_render=support['same_render'],snapshot=support['snapshot'],real_replay=support['real_independent_replay'],numerics_equal_v3=support['numerics_equal_v3'],v3_manual_arithmetic_preserved=str(HERE/'recheck_v3_independent_calculations.json')),missing_steps=[dict(id=q['id'],status=q['check_status'],description=q['details']) for q in remaining],findings=findings,artifact_integrity=dict(v4_and_review_inputs=support['artifacts'],protected188=support['protected188'],runtime51=support['runtime51']),limits=['Accepts transparent conditional RF model/artifact correctness, not an investment accepted/rejected conclusion, forecast-accuracy guarantee or whole-product E2E completion.','No new actual source facts or recalibration;325 claims/53 parameters are inherited from sealed v3 by exact equality.','Date upper bounds are availability assertions only, precise public days and FY2025 official sameSHA remain unverified.','R06/R09/R10/R11 product/source gaps and R07/R12 exact-date/calibration limitations persist.','Initial reviewer helper expected JSON confidence warning literal in standard Markdown; that assumption was corrected to actual limited/risk disclosure and exact deterministic rendering. Failure remains logged; no execution input/output changed.','No reviewer source/provider/config/runtime/producer writes. Future owner cleanup/archive belongs to MAIN.'],command_index=str(HERE/'commands/index.jsonl'),execution_command_index=m['command_index'])
(HERE/'recheck_v4.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
lines=['# 腾讯 HK00700 v4 独立变更闭包复查','',f'- 时间：{report["reviewed_at"]}；reviewer：`/root/rf_hk_independent_review`；executor：`{m["agent_id"]}`','- **本次修复：PASS。模型接受：有条件、有局限。整体产品 E2E：PARTIAL。**','- HK-V3-R01 与 HK-R02 分类闭包已关闭。初审和 sealed v3 原结论及文件保留。','', '## 已验证','', '- input 只有声明的 7 项分类/说明/版本变化。325 条 claims、53 项参数全文、来源/日期/历史/认定/沟通记录与 sealed v3 完全相同；未重复原文和全年历史审查。','- NetEase 节点改为 `contrary`，文字明确跨公司 analogical 竞争风险、NET/perimeter 不同，没有腾讯份额/替代/量价或增长幅度测量，不能三角验证腾讯正向机制。','- 实际 Games 在排名和详细驱动树均为 `limited`；JSON 中置信度限制恢复，score 与 components 保持 64。Markdown 为标准同源渲染，显示 limited、风险/contrary 与无 triangulation 信用；其标准模板不逐字输出该条 JSON warning。','- strong input-required、同源 render、独立 TEMP 实际 CLI、snapshot 和 actual registry audit/chain/anchors 全部通过。45 路径、9 合计/CAGR/增量、15 敏感性及全部分配数值完全不变。','- 188 个旧文件（含 sealed v3）SHA/bytes 不变；51 installed/canonical runtime 一致且不变。没有生产源、source-facts、配置、运行时或原执行产物写操作。','', '## 保留限制','', '| 项目 | 最终状态 |','|---|---|','| R06：FY2025 官网同 SHA / 官方原件认证 | BLOCKED |','| R07：年度/H1/Corporate 精确公开日 | UNKNOWN；只接受 2026-10-08 可用上界 |','| R09：Dayu 有界缺文档下载→复用 | BLOCKED |','| R10：ET 电话会正文 / 完整公告区间 | BLOCKED / PARTIAL |','| R11：HK canonical Worker / narrative 消费 | BLOCKED；既有 MSFT 当前读不等于 HK 本轮执行 |','| R12：未来准确度 / 参考类校准 | 未建立；条件 fallback 与 H2 要求已充分披露 |','', '## 检查记录','', '| 检查 | 状态 | 内容 |','|---|---|---|']
lines += ['| '+q['id']+' '+q['topic']+' | '+q['status']+' | '+q['details'].replace('|','/')+' |' for q in checks]
lines += ['','支持文件：recheck_v4_support.json（7项独立diff、188项SHA、51runtime、实际命令和进程、独立重跑及registry）；recheck_v4.json（逐项结论和关闭/剩余清单）。','', '此处接受条件模型的工程和证据质量闭包，不表示整条资料供应产品或未来预测准确性已通过。MAIN 可据此归总并处理归档/清理；本 reviewer 不修改 sealed 历史路径。','']
(HERE/'recheck_v4.md').write_text('\n'.join(lines),encoding='utf-8')
assert len(checks)==12 and all(q['status']=='PASS' for q in checks[:8])
assert sha(HERE/'recheck_v3.json')==m['review_inputs'][1]['sha256']
assert sha(HERE/'recheck_v3.md')==m['review_inputs'][0]['sha256']
integrity=dict(repair_scope_verdict='PASS',overall='PARTIAL',model_acceptance=report['model_acceptance'],checks=12,closed=['HK-V3-R01','HK-R02'],remaining=[q['id'] for q in remaining],sealed_v3_unchanged=True,protected188=True,runtime51_unchanged=True,report_sha256={'recheck_v4.json':sha(HERE/'recheck_v4.json'),'recheck_v4.md':sha(HERE/'recheck_v4.md')})
(HERE/'recheck_v4_integrity.json').write_text(json.dumps(integrity,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps(integrity,ensure_ascii=False))
